### ISSUE TITLE
Buttons - including 'Help' - do not display in preferences.

### ISSUE THREAD

**Issue by revad** [revad/use_bcc_instead_C#4]
Preference  buttons have vanished.

This is because of the removal of prefwindow:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522778#c54

See Geoff Lankow's response.

**Comment by revad** [comment]
Probably WONTFIX.
It would be better to have this text on ATN, localised if possible.

**Comment by revad** [comment]
@MaxKoll 
I wrote a sed script to convert the help.dtd files into text that could be put into ATN and appear on the localised addon description.  Running it on the English file I get this
https://gist.github.com/revad/ceba68a2a80f47ce0eb71a1b2a04f98f

Running it on the German file I get this
https://gist.github.com/revad/65093a7f2b5aae723871a53198ee93fd

Does that look OK? The html tags will probably change.

I don't want to alter the structure of the text (though I left some paragraphs out) because I don't want to change translations in languages I don't know - like Chinese! 

I am currently thinking of publishing it when TB68 is released, but it will depend on what other changes are required before then.

**Comment by MaxKoll** [comment]
I notice two things:
- Line 15 should end with a colon.
- There is a closing `</b>` tag at the end of every line, even if there is no opening tag.

Otherwise it looks fine.

While reading the translation again, I found a typo as well as a clumsy sentence that needs rephrasing. Should I propose changes to the original translation files or directly to the gists above?

**Comment by revad** [comment]
Thanks. I may need to add the colon manually: it may not be correct in Chinese (and/or there seems to already be one).
The </b> tags are deliberate, to simplify the script. I don't think they will matter.
Please change the original DE translation - I'll rerun the script on all languages eventually.

Geoff Lankow says he will be zapping more of the preferences, but I don't know when.
https://bugzilla.mozilla.org/show_bug.cgi?id=1476259#c27

**Comment by revad** [comment]
Bug 1527770 landed, which removed the css for <prefwindow>
Added that back in (based on css in TB66B) as AddonOptions.css
Also removed the preferences button code.

Preferences work in 67A for now.

**Comment by revad** [comment]
Nope. Preferences don't work.
Closing this and opening #6

**Comment by revad** [comment]
After fixing  #6 changed &lt;prefwindow&gt; for  &lt;dialog&gt; so the help button and window now appear.
Removed the 'platform' and 'notes' sections from the help window text.
Will still reproduce that on ATN if I publish.
